version: '3'

volumes:
  mysql:

services:
  droopler:
    image: droptica/droopler:latest
    environment:
      - DB_HOST=mysql
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=pass

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
